/* eslint-disable react-hooks/rules-of-hooks */
import Head from 'next/head';
import Link from 'next/link';
import { useEffect, useState } from 'react';
import { getPosts } from '../../../services/getPosts';
import { getTodos } from '../../../services/getTodos';
import logger from '../../../utils/logger';
import MyTodos from '../../MyTodos';
import styles from './../../../styles/Home.module.css';

export async function getStaticProps({ locale }) {
  try {
    const todosData = await getTodos(5);
    const postsData = await getPosts(5);
    return {
      props: {
        todosData,
        postsData,
        locale
      },
      revalidate: 60
    };
  } catch (err) {
    logger.error('home page error ++++++++++++++++++++> ', err?.message);
    return {
      props: {
        notFound: true
      },
      revalidate: 5
    };
  }
}

function Home({ todosData, locale }) {
  const [posts, setPosts] = useState([]);
  useEffect(() => {
    try {
      async function fetchData() {
        const res = await getPosts(5);
        setPosts(res);
      }
      fetchData();
    } catch (err) {
      logger.error('Failed to get posts data on client side', err);
    }
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main>
        <MyTodos
          todosData={todosData}
          locale={locale}
        />
        <hr />
        <h1>My Posts - {locale}</h1>
        {posts?.length ? (
          <section>
            {posts?.map((item) => {
              return (
                <div
                  key={item.id}
                  className="blog-items">
                  <Link
                    href={{
                      pathname: `/posts/${item.id}`
                    }}>
                    <a>{item.title}</a>
                  </Link>
                </div>
              );
            })}
          </section>
        ) : (
          <p>...loading posts</p>
        )}
      </main>
    </div>
  );
}

export default Home;
